### Tiny data for tests only
tiny_h5:
    data_root: ../../../data/
    data_format: h5
    train_data: ../../../data/tiny_h5/train.h5
    valid_data: ../../../data/tiny_h5/valid.h5
    test_data: ../../../data/tiny_h5/test.h5

tiny_csv:
    data_root: ../../../data/
    data_format: csv
    train_data: ../../../data/tiny_csv/train_sample.csv
    valid_data: ../../../data/tiny_csv/valid_sample.csv
    test_data: ../../../data/tiny_csv/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                 "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                 active: True, dtype: str, type: categorical}]
    label_col: {name: clk, dtype: float}

tiny:
    data_root: ../../data/
    data_format: csv
    train_data: ../../data/tiny_csv/train_sample.csv
    valid_data: ../../data/tiny_csv/valid_sample.csv
    test_data: ../../data/tiny_csv/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                 "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"],
                 active: True, dtype: str, type: categorical}]
    label_col: {name: clk, dtype: float}


Avazu_x4_h5:
    data_format: h5
    data_root: ../../../data/
    feature_cols:
        - { active: false, dtype: str, name: id, type: categorical }
        - { active: true, dtype: str, name: hour, preprocess: convert_hour, type: categorical }
        - active: true
          dtype: str
          name: [ C1, banner_pos, site_id, site_domain, site_category, app_id, app_domain,
                  app_category, device_id, device_ip, device_model, device_type, device_conn_type,
                  C14, C15, C16, C17, C18, C19, C20, C21 ]
          type: categorical
        - { active: true, dtype: str, name: weekday, preprocess: convert_weekday, type: categorical }
        - { active: true, dtype: str, name: weekend, preprocess: convert_weekend, type: categorical }
    label_col: { dtype: float, name: click }
    min_categr_count: 2
    test_data: ../../../data/Avazu_x4_h5/test.h5
    train_data: ../../../data/Avazu_x4_h5/train.h5
    valid_data: ../../../data/Avazu_x4_h5/valid.h5

Criteo_x4_h5:
    data_format: h5
    data_root: ../../../data/
    feature_cols:
    -   active: true
        dtype: float
        fill_na: 0
        name: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
        preprocess: convert_to_bucket
        type: categorical
    -   active: true
        dtype: str
        fill_na: ''
        name: [C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16,
            C17, C18, C19, C20, C21, C22, C23, C24, C25, C26]
        type: categorical
    label_col: {dtype: float, name: Label}
    min_categr_count: 2
    test_data: ../../../data/Criteo_x4_h5/test.h5
    train_data: ../../../data/Criteo_x4_h5/train.h5
    valid_data: ../../../data/Criteo_x4_h5/valid.h5

Movielenslatest_x1:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
    -   active: true
        dtype: float
        name: [user_id, item_id, tag_id]
        type: categorical
    label_col: {dtype: float, name: label}
    min_categr_count: 2
    test_data: ../../../data/MovielensLatest_x1/test.csv
    train_data: ../../../data/MovielensLatest_x1/train.csv
    valid_data: ../../../data/MovielensLatest_x1/valid.csv

Movielenslatest_x1_h5:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
    -   active: true
        dtype: float
        name: [user_id, item_id, tag_id]
        type: categorical
    label_col: {dtype: float, name: label}
    min_categr_count: 2
    test_data: ../../../data/MovielensLatest_x1_h5/test.h5
    train_data: ../../../data/MovielensLatest_x1_h5/train.h5
    valid_data: ../../../data/MovielensLatest_x1_h5/valid.h5