Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

CETN_Criteo:
    model: CETN
    dataset_id: Criteo_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 5.e-4
    embedding_regularizer: 1.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    fi_hidden_units: [1024, 512, 256]
    w_hidden_units: [512, 512]
    hidden_activations: [mish, leaky_relu, prelu]
    through: True
    perturbed: False
    eps: 1.e-5
    alpha: 0.4
    beta: 0.4
    delta: 0.4
    cl_temperature: 0.4
    W_net_dropout: 0.2
    V_net_dropout: 0.2
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

CETN_Avazu:
    model: CETN
    dataset_id: Avazu_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    fi_hidden_units: [512, 512, 512]
    w_hidden_units: [512, 512, 512]
    hidden_activations: [leaky_relu, leaky_relu, leaky_relu]
    through: True
    perturbed: False
    eps: 1.e-5
    alpha: 0.1
    beta: 0.6
    delta: 0.1
    cl_temperature: 0.5
    W_net_dropout: 0
    V_net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

CETN_Movielens:
    model: CETN
    dataset_id: Movielenslatest_x1_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    w_hidden_units: [400]
    fi_hidden_units: [400, 200]
    hidden_activations: [dice, dice, dice]
    through: True
    perturbed: False
    eps: 1.e-5
    alpha: 0.2
    beta: 0.7
    delta: 0.6
    cl_temperature: 0.2
    W_net_dropout: 0.2
    V_net_dropout: 0.2
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
