### Tiny data for tests only
tiny_h5:
    data_root: ../../data/
    data_format: h5
    train_data: ../../data/tiny_h5/train.h5
    valid_data: ../../data/tiny_h5/valid.h5
    test_data: ../../data/tiny_h5/test.h5

Avazu_x4_h5:
    data_format: h5
    data_root: ../../data/
    feature_cols:
        - { active: false, dtype: str, name: id, type: categorical }
        - { active: true, dtype: str, name: hour, preprocess: convert_hour, type: categorical }
        - active: true
          dtype: str
          name: [ C1, banner_pos, site_id, site_domain, site_category, app_id, app_domain,
                  app_category, device_id, device_ip, device_model, device_type, device_conn_type,
                  C14, C15, C16, C17, C18, C19, C20, C21 ]
          type: categorical
        - { active: true, dtype: str, name: weekday, preprocess: convert_weekday, type: categorical }
        - { active: true, dtype: str, name: weekend, preprocess: convert_weekend, type: categorical }
    label_col: { dtype: float, name: click }
    min_categr_count: 2
    test_data: ../../data/Avazu_x4_h5/test.h5
    train_data: ../../data/Avazu_x4_h5/train.h5
    valid_data: ../../data/Avazu_x4_h5/valid.h5

Criteo_x4_h5:
    data_format: h5
    data_root: ../../data/
    feature_cols:
    -   active: true
        dtype: float
        fill_na: 0
        name: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
        preprocess: convert_to_bucket
        type: categorical
    -   active: true
        dtype: str
        fill_na: ''
        name: [C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16,
            C17, C18, C19, C20, C21, C22, C23, C24, C25, C26]
        type: categorical
    label_col: {dtype: float, name: Label}
    min_categr_count: 2
    test_data: ../../data/Criteo_x4_h5/test.h5
    train_data: ../../data/Criteo_x4_h5/train.h5
    valid_data: ../../data/Criteo_x4_h5/valid.h5

Movielenslatest_x1_h5:
    data_format: csv
    data_root: ../../data/
    feature_cols:
    -   active: true
        dtype: float
        name: [user_id, item_id, tag_id]
        type: categorical
    label_col: {dtype: float, name: label}
    min_categr_count: 2
    test_data: ../../data/MovielensLatest_x1_h5/test.h5
    train_data: ../../data/MovielensLatest_x1_h5/train.h5
    valid_data: ../../data/MovielensLatest_x1_h5/valid.h5

Frappe_x1_h5:
    data_format: h5
    data_root: ../../data/
    feature_cols:
    -   active: true
        dtype: float
        name: [user, item, daytime, weekday, isweekend, homework, cost, weather, country,
            city]
        type: categorical
    label_col: {dtype: float, name: label}
    min_categr_count: 2
    test_data: ../../data/Frappe_x1_h5/test.h5
    train_data: ../../data/Frappe_x1_h5/train.h5
    valid_data: ../../data/Frappe_x1_h5/valid.h5

kuaivideo_x1:
    data_format: csv
    data_root: ../../data/KuaiShou/
    feature_cols:
    - {active: true, dtype: int, name: group_id, preprocess: copy_from(user_id), remap: false,
        type: meta}
    - {active: true, dtype: str, name: user_id, type: categorical}
    - {active: true, dtype: str, name: item_id, type: categorical}
    - {active: true, dtype: str, embedding_dim: 64, min_categr_count: 1, name: item_emb,
        preprocess: copy_from(item_id), pretrained_emb: ../../data/KuaiVideo_x1/item_visual_emb_dim64.h5,
        type: categorical}
    - {active: true, dtype: str, max_len: 100, name: pos_items, padding: pre, share_embedding: item_id,
        splitter: ^, type: sequence}
    - {active: true, dtype: str, max_len: 100, name: neg_items, padding: pre, share_embedding: item_id,
        splitter: ^, type: sequence}
    - {active: true, dtype: str, embedding_dim: 64, max_len: 100, min_categr_count: 1,
        name: pos_items_emb, padding: pre, preprocess: copy_from(pos_items), pretrained_emb: ../../data/KuaiVideo_x1/item_visual_emb_dim64.h5,
        share_embedding: item_emb, splitter: ^, type: sequence}
    - {active: true, dtype: str, embedding_dim: 64, max_len: 100, min_categr_count: 1,
        name: neg_items_emb, padding: pre, preprocess: copy_from(neg_items), pretrained_emb: ../../data/KuaiVideo_x1/item_visual_emb_dim64.h5,
        share_embedding: item_emb, splitter: ^, type: sequence}
    label_col: {dtype: float, name: is_click}
    min_categr_count: 10
    test_data: ../../data/KuaiVideo_x1/test.csv
    train_data: ../../data/KuaiVideo_x1/train.csv
    valid_data: ../../data/KuaiVideo_x1/test.csv

microvideo1.7m_x1:
    data_format: csv
    data_root: ../../data/MicroVideo1.7M/
    feature_cols:
    - {active: true, dtype: int, name: group_id, preprocess: copy_from(user_id), remap: false,
        type: meta}
    - {active: true, dtype: str, name: user_id, type: categorical}
    - {active: true, dtype: str, embedding_dim: 64, name: item_id, pretrained_emb: ../../data/MicroVideo1.7M_x1/item_image_emb_dim64.h5,
        type: categorical}
    - {active: true, dtype: str, name: cate_id, type: categorical}
    - {active: true, dtype: str, embedding_dim: 64, max_len: 100, name: clicked_items,
        padding: pre, pretrained_emb: ../../data/MicroVideo1.7M_x1/item_image_emb_dim64.h5,
        splitter: ^, type: sequence}
    - {active: true, dtype: str, max_len: 100, name: clicked_categories, padding: pre,
        share_embedding: cate_id, splitter: ^, type: sequence}
    - {active: false, dtype: str, name: timestamp, type: categorical}
    label_col: {dtype: float, name: is_click}
    min_categr_count: 1
    test_data: ../../data/MicroVideo1.7M_x1/test.csv
    train_data: ../../data/MicroVideo1.7M_x1/train.csv
    valid_data: ../../data/MicroVideo1.7M_x1/test.csv

ML-1M:
    data_format: csv
    data_root: ../../data/
    feature_cols:
        - { name: group_id, active: True, dtype: int, type: meta, preprocess: "copy_from(UserID)", remap: False }
        - active: true
          dtype: float
          name: [ UserID, Gender, Age, Occupation, MovieID ]
          type: categorical
    label_col: { dtype: float, name: Label }
    min_categr_count: 2
    test_data: ../../data/ML-1M/test.csv
    train_data: ../../data/ML-1M/train.csv
    valid_data: ../../data/ML-1M/valid.csv

KKBox_x1_h5:
    data_format: h5
    data_root: ../../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [msno, song_id, source_system_tab, source_screen_name, source_type,
            city, gender, registered_via, language]
        type: categorical
    - {active: true, dtype: str, encoder: MaskedSumPooling, max_len: 3, name: genre_ids,
        type: sequence}
    - {active: true, dtype: str, encoder: MaskedSumPooling, max_len: 3, name: artist_name,
        type: sequence}
    - {active: true, dtype: str, name: isrc, preprocess: extract_country_code, type: categorical}
    - {active: true, dtype: str, name: bd, preprocess: bucketize_age, type: categorical}
    label_col: {dtype: float, name: label}
    min_categr_count: 2
    test_data: ../../data/KKBox_x1_h5/test.h5
    train_data: ../../data/KKBox_x1_h5/train.h5
    valid_data: ../../data/KKBox_x1_h5/valid.h5