Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

EulerNet_default: # This is a config template
    model: EulerNet
    dataset_id: Avazu_x4_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-08
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 17
    logarithmic_neurons: 1200
    afn_hidden_units: [1024, 1024, 1024]
    afn_activations: relu
    afn_dropout: 0
    ensemble_dnn: True
    dnn_hidden_units: [1024, 1024, 1024]
    dnn_activations: relu
    dnn_dropout: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_kuaivideo_x1: # This is a config template
    model: EulerNet
    dataset_id: kuaivideo_x1
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 64
    order_list: [7, 7, 7]
    dropout_explicit: 0.1
    dropout_implicit: 0.1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_microvideo1.7m_x1: # This is a config template
    model: EulerNet
    dataset_id: microvideo1.7m_x1
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 64
    order_list: [5, 5, 5]
    dropout_explicit: 0.1
    dropout_implicit: 0.1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_Avazu: # This is a config template
    model: EulerNet
    dataset_id: Avazu_x4_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    order_list: [23, 23, 23]
    dropout_explicit: 0
    dropout_implicit: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_Criteo: # This is a config template
    model: EulerNet
    dataset_id: Criteo_x4_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    order_list: [39, 39, 39, 39]
    dropout_explicit: 0.1
    dropout_implicit: 0.2
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_Movielenslatest_x1_h5: # This is a config template
    model: EulerNet
    dataset_id: Movielenslatest_x1_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-2
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    order_list: [3]
    dropout_explicit: 0
    dropout_implicit: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_Frappe_x1_h5: # This is a config template
    model: EulerNet
    dataset_id: Frappe_x1_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-2
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    order_list: [10, 10, 10]
    dropout_explicit: 0
    dropout_implicit: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

EulerNet_ML-1M: # This is a config template
    model: EulerNet
    dataset_id: ML-1M
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-2
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    order_list: [5, 5, 5]
    dropout_explicit: 0
    dropout_implicit: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'


EulerNet_KKBox_x1_h5: # This is a config template
    model: EulerNet
    dataset_id: KKBox_x1_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-2
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    order_list: [13, 13, 13]
    dropout_explicit: 0
    dropout_implicit: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'